# Generated by Django 5.1 on 2024-12-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(choices=[('Science and Information Technology', 'Science and Information Technology'), ('Business and Entrepreneurship', 'Business and Entrepreneurship'), ('Engineering', 'Engineering'), ('Humanities and Social Sciences', 'Humanities and Social Sciences'), ('Health and Life Sciences', 'Health and Life Sciences')], max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.CharField(choices=[('Summer', 'Summer'), ('Fall', 'Fall'), ('Spring', 'Spring')], max_length=100)),
                ('exam_type', models.CharField(choices=[('Mid Term', 'Mid Term'), ('Final', 'Final')], max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=2024)),
            ],
        ),
    ]
