# Generated by Django 5.1 on 2024-12-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_question_created_at_question_question_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='semester',
            field=models.CharField(choices=[('All', 'All'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Spring', 'Spring')], max_length=100),
        ),
    ]
