# Generated by Django 5.1 on 2025-01-02 17:47

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_question_question_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_file',
            field=models.FileField(max_length=255, upload_to=dashboard.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='question',
            name='semester',
            field=models.CharField(choices=[('All', 'All'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], max_length=100),
        ),
    ]
