# Generated by Django 5.1 on 2025-01-03 19:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_user_attribute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Attribute',
            new_name='UserAttribute',
        ),
    ]
