# Generated by Django 5.1 on 2024-12-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_student_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cover_pic',
            field=models.ImageField(blank=True, null=True, upload_to='cover_pic/'),
        ),
        migrations.AddField(
            model_name='student',
            name='social_media_handle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
