# Generated by Django 5.1 on 2024-12-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_student_cover_pic_student_social_media_handle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cover_pic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='social_media_handle',
        ),
        migrations.AddField(
            model_name='student',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
